spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: ${APP_USERNAME:user}
      password: ${APP_PASSWORD:pass}
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.example.mooneys.mapper: DEBUG

mybatis:
  type-aliases-package: com.example.mooneys.entity
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/custom/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  error:
    include-stacktrace: always

debug: true
